# Generated by Django 2.1.7 on 2019-03-08 07:44

import BookListApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='type_of_book',
            field=models.CharField(choices=[(BookListApp.models.BookType('Novel'), 'Novel'), (BookListApp.models.BookType('Documentation'), 'Documentation'), (BookListApp.models.BookType('Other'), 'Other')], default=BookListApp.models.BookType('Other'), max_length=15),
        ),
    ]
