# Generated by Django 2.1.7 on 2019-03-08 07:49

import BookListApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListApp', '0002_auto_20190308_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='type_of_book',
            field=models.CharField(blank=True, choices=[(BookListApp.models.BookType('Novel'), 'Novel'), (BookListApp.models.BookType('Documentation'), 'Documentation'), (BookListApp.models.BookType('Other'), 'Other')], max_length=15, null=True),
        ),
    ]
