# Generated by Django 2.1.7 on 2019-03-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListApp', '0004_auto_20190308_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type_of_book',
            field=models.CharField(blank=True, choices=[('NOV', 'Novel'), ('DOC', 'Documentation'), ('OTH', 'Other')], max_length=3, null=True),
        ),
    ]
