# Generated by Django 2.1.7 on 2019-03-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListApp', '0005_auto_20190308_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type_of_book',
            field=models.CharField(blank=True, choices=[('Category', (('NOV', 'Novel'), ('DOC', 'Documentation'), ('OTH', 'Other')))], max_length=3, null=True),
        ),
    ]
