# Generated by Django 2.1.7 on 2019-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListApp', '0006_auto_20190309_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type_of_book',
            field=models.CharField(blank=True, choices=[('NOV', 'Novel'), ('DOC', 'Documentation'), ('OTH', 'Other')], default='Category', max_length=3, null=True),
        ),
    ]
